name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Rubocop checks
      uses: gimenete/rubocop-action@1.0

    - name: Rubocop Linter Action
      uses: andrewmcodes/rubocop-linter-action@v1.0.5

    - name: Rubocop Code Checks
      uses: lyttco/github-actions-rubocop@1.3
        env:
          GITHUB_TOKEN: ${GITHUB_TOKEN}
